### ISSUE TITLE
What are the credentials referenced in the example code?

### ISSUE THREAD

**Issue by preeth1** [rblopes/godot-twitch-irc-client#2]
This is an excellent plugin, I am just not understanding which credentials to use in the readme example. I am trying to run it with my own values, and I get a "Login authentication failed" error. I think if this is clarified, it'll be really easy for people to get started with this plugin.

The following lines have the unclear variables:
```
func _on_connection_opened() -> void:
  # Replace <nick> and <OAuth Token> with actual values.
  $TwitchIRCClient.authenticate("<nick>", "<OAuth Token>")
```
and
```
func _on_authentication_succeeded() -> void:
  # Replace <twitch channel> with an actual value.
  $TwitchIRCClient.join("#<twitch channel>")
```
My questions are:
1. What is "Nick" referring to? The application name, the username of the developer account, or something else?
2. Is the "OAuth Token" supposed to come from here: https://twitchapps.com/tmi/, or should I get this from the developer console somewhere?
3. Is "twitch channel" referring to the channel that I want to run this api from?
4. I have a client ID and client secret from creating an app- are these values supposed to be entered in this code somewhere?

Thank you! Once this is clarified, I'm happy to make a pull request with some updates to the readme :)

**Comment by preeth1** [comment]
To add slightly more info, I am just trying to get the "!helloworld" example running, so presumably I don't need a ton of credentials set up for that?

**Comment by preeth1** [comment]
A couple things I found through trial and error! To get the !helloworld example working:
1. you don't need to create an app in the developer console
2. you do need to generate an oauth token here: https://twitchapps.com/tmi/
3. IMPORTANT: it will be generated in the form "oauth:123456". In the code, you JUST need the "123456" portion of it, if you include the "oauth:", it will not work!
4. I could modify "Nick" to be anything and it still worked (so the purpose of this variable isn't clear to me yet)

**Comment by rblopes** [comment]
Hi. Thanks for testing the plugin and reporting these issues. Answering your questions:

1. It's **good practice** to pass the account name you've generated the OAuth token for as a nick. The `NICK` IRC message is a requirement of the RFC1459 (which, to be fair, I'm not sure Twitch follows closely.)

2. You must pass the OAuth token, omitting the `oauth:` part.

3. It's the Twitch channel whose chat you want to interact with. Remember that, at the moment, joining and managing several channels at once is not supported. Also, you need the `chat:read` OAuth scope to read messages, and `chat:edit` to send replies.

4. The plugin doesn't need your client ID or secret to use it.

I have updated the README accordingly.

---

There are a few ways to obtain OAuth tokens, which are described in greater detail on the [Twitch developer docs](https://dev.twitch.tv/docs/authentication/).

Earlier revisions of the plugin's documentation briefly mentioned `https://twitchapps.com/tmi/` as a way to obtain OAuth tokens, but I don't recommend it anymore. That site is an independent effort, and it could be decommissioned anytime (btw, at the moment I'm writing this, I'm getting an HTTP 403 error accessing that site's address, omitting the `/tmi` part, which is a bad sign.)

Tokens obtained there use the OAuth Implicit Grant Flow method, which is easy to implement, generated tokens last indefinitely (but expire, eventually) and is OK for testing purposes. The reason "you don't need" to register an app in this case is because you're authorizing their app to do stuff on your behalf, as you would with any other Twitch apps (StreamElements, Nightbot and others, for example.)

For this reason you ideally should register your own app and generate your tokens through it. Easier said than done, I'm sorry for that... You could try using the [Twitch CLI](https://github.com/twitchdev/twitch-cli/releases), but tokens created with it use Authorization Code Grant Flow that last for about 4 hours, but at least you can refresh them manually.

I've been working on a prototype of a plugin to help with OAuth Authorization Code Grant Flow recently, complete with token validation and refreshing, but it still needs testing and I haven't decided yet how its API should look like yet. (And I've not much free time lately, that's why its taking me forever to finish it.)
